version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-tasks
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iryna_sadovska
      - MONGO_INITDB_ROOT_PASSWORD=iryna_sadovska
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
